# Generated by Django 3.0.3 on 2020-03-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_customer_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
