# Generated by Django 3.0.3 on 2020-03-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDefault', '0002_auto_20200311_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empleado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserDefault.Empleado'),
        ),
    ]
