# Generated by Django 3.0.3 on 2020-03-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDefault', '0015_auto_20200311_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariomedico',
            old_name='numero_de_trabajo',
            new_name='numero',
        ),
    ]
