# Generated by Django 3.0.3 on 2020-03-12 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserDefault', '0018_auto_20200312_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserDefault.Empleado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariomedico',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
